### PR TITLE
initial circleci conf

### PR DESCRIPTION
**Pull request by simonhoye**

### CODE REVIEW

**Comment by jvehent** [comment]
Hi Simon. I hope you enjoy the book and can run through the examples easily. Cheers :tada:

**Comment by simonhoye** [comment]
Whoops!

Since you asked, I am really enjoying the book however, I cannot get the example in chapter 3, listing 3.1 to work, where you add the additional steps in the CI config to run ZAProxy against the app. I'm using the chapter 2 app source code and the ZAProxy passes every time and doesn't fail on the 4 riles as expected.

**Comment by jvehent** [comment]
Try apply this patch to your circleci config: https://github.com/Securing-DevOps/invoicer-chapter3/commit/1078393b14adcaf6ff0d5d7582afcc4368976e9b

ZAP should run properly after this. If not, could you link me to your circle run?

**Comment by simonhoye** [comment]
Thanks for the quick reply, I tried that patch and received the same result, heres a link to the CI build https://circleci.com/gh/simonhoye/invoicer-chapter2/36

**Comment by jvehent** [comment]
Good catch. I inadvertently merged the security headers added in chapter 3 into the chapter 2 repository. I'll fix this shortly. Thanks for letting me know!

**Comment by jvehent** [comment]
I've removed those security headers from the invoicer in chapter 2. Try rebasing your fork and the zap baseline should now fail: https://github.com/Securing-DevOps/invoicer-chapter2/commit/310bf66cf4fdf418229547d2bd751e856db4912f

**Comment by simonhoye** [comment]
Thank you so much for your help, I've got it working now!! Although ZAP doesn't seem to be using the custom config file as it only warns and doesn't fail, which seems to be an issue with ZAP itself.

Looking forward to continuing on with the examples in the book now :+1:

**Pull request closed without merging**
